[package]
name = "feet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22"
term_size = "0.3.2"
tui = "0.17.0"
unicode-segmentation = "1.9.0"
